server:
  port: 8888

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: oauth2-client-app
            client-secret: 44oQcipHJoLQTUFLBqeL2dgFp5oykIMF
            client-name: oauth2-client-app
            redirect-uri: http://localhost:8888/login/oauth2/code/keycloak
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            scope: profile, email
        provider:
          keycloak:
            authorization-uri: http://localhost:8180/realms/oauth2/protocol/openid-connect/auth
            token-uri: http://localhost:8180/realms/oauth2/protocol/openid-connect/token
            issuer-uri: http://localhost:8180/realms/oauth2
            user-info-uri: http://localhost:8180/realms/oauth2/protocol/openid-connect/userinfo
            jwk-set-uri: http://localhost:8180/realms/oauth2/protocol/openid-connect/certs
            user-name-attribute: preferred_username
